"""add sentences_text to words, drop sentences table

Revision ID: 0709161a113d
Revises: b2fecb4cf748
Create Date: 2026-01-25 13:43:06.243865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0709161a113d'
down_revision: Union[str, Sequence[str], None] = 'b2fecb4cf748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_word_id'), table_name='sentences')
    op.drop_table('sentences')
    op.add_column('words', sa.Column('sentences_text', sa.String(length=4000), nullable=True, comment='Примеры предложений от LLM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'sentences_text')
    op.create_table('sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sentence_en', sa.VARCHAR(length=1000), autoincrement=False, nullable=False, comment='Предложение на английском'),
    sa.Column('sentence_ru', sa.VARCHAR(length=1000), autoincrement=False, nullable=False, comment='Перевод предложения'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('sentences_word_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sentences_pkey'))
    )
    op.create_index(op.f('ix_sentences_word_id'), 'sentences', ['word_id'], unique=False)
    # ### end Alembic commands ###
