"""add sentences table

Revision ID: b2fecb4cf748
Revises: 21edf9a13552
Create Date: 2026-01-25 10:47:47.113823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fecb4cf748'
down_revision: Union[str, Sequence[str], None] = '21edf9a13552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sentence_en', sa.String(length=1000), nullable=False, comment='Предложение на английском'),
    sa.Column('sentence_ru', sa.String(length=1000), nullable=False, comment='Перевод предложения'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_word_id'), 'sentences', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_word_id'), table_name='sentences')
    op.drop_table('sentences')
    # ### end Alembic commands ###
